### ISSUE TITLE
[First Timer Only] - Create PR with adding your name to this repo

### ISSUE THREAD

**Issue by mazipan** [mazipan/hello-open-source#1]
Read complete guidance in `readme.md`

**Comment by akashraj98** [comment]
@mazipan I will add my name

**Comment by ngengesenior** [comment]
I will add my name

**Comment by johncoleman83** [comment]
what's will you use your data collection for? This has a real spammy vibe to it?

**Comment by mazipan** [comment]
That's why this is only for beginners, this have no use for advanced users.

**Comment by mazipan** [comment]
There's no requirement to add your real data, this is just for git flow practices

**Comment by JukMR** [comment]
I will add my name :smile:

**Comment by GunnlaugurCalvi** [comment]
Added  😄

**Comment by webconnector** [comment]
Am adding mine right away

**Comment by hidalgo-vntu** [comment]
add name to repo #203

**Comment by valdeadmario** [comment]
add #204

**Comment by greyGroot** [comment]
please add [#288](https://github.com/mazipan/hello-open-source/pull/288)

**Comment by AnjaliSharma1234** [comment]
Add my name

**Comment by webconnector** [comment]
Loya I.G Blaise

**Comment by AnjaliSharma1234** [comment]
What is the further procedure? I got this email.

**Comment by dscntr17** [comment]
I would like to try this.

**Comment by paulis-reece** [comment]
Can I try this?

**Comment by singhambuj** [comment]
I will add my name ^=^

**Comment by akshat8171** [comment]
i would like to try this

**Comment by Khushi-24** [comment]
I will add my name.

**Comment by aufalmarom** [comment]
i will add my name, try for the first time contribute to open source.

**Comment by Shubham56-droid** [comment]
i will add my  name

**Comment by mukki00** [comment]
Please assign my name to this issue

**Comment by SAM32ASD** [comment]
D'accord c'est compris

**Comment by Ayush0431** [comment]
Hey @mazipan I was looking for practice and I found this repo for contributing ,I have made a pull request please check it😊.
Cheers✌

**Comment by designeralabi** [comment]
hello, am a first-timer on open source project so found your repo and will like to contribute, thanks so i will add my name

**Comment by ojasaklechayt** [comment]
> Read complete guidance in `readme.md`

I will write name please allow

**Comment by Alascam** [comment]
I want leave my me

**Comment by Arsaluddin** [comment]
I will add my name !😃

**Comment by Mbiakop1** [comment]
Hi, am happy to be here.
I will add my name !😃

**Comment by Mbiakop1** [comment]
Hello everyone, please I have been trying to add my name. I made several PRs but it keeps failing. Am not sure if doing wrong can someone help? 
This is the message I keep receiving in my email.
[mazipan/hello-open-source] PR run failed: CI - create mbiakop.js (8f1ff5f)

**Comment by nayanapardhekar** [comment]
Hey, may I add my name too.

**Comment by SAM32ASD** [comment]
That's good. How are feeling good

**Comment by Arnab7456** [comment]
Hey, may I add my name too.

**Comment by SAM32ASD** [comment]
Ok

**Comment by sdhrrr** [comment]
I want to add my name!
