### ISSUE TITLE
Translation into several languages

### ISSUE THREAD

**Issue by mazipan** [mazipan/hello-open-source#195]
It's cool to support multiple languages since so many countries doesn't know English well.

Here are some of main language that we need to support first, but not limited with other languages:

- [ ] China
- [ ] Japan
- [x] Korea

**Comment by robwgreenjr** [comment]
I can grab this. I don't speak the languages but I know how to use the google translator.

**Comment by nickjlee** [comment]
hello~ I noticed @robwgreenjr already submitted a PR #196 for these translations, but I'm a native Korean speaker and saw a few things in there that did not translate correctly. I'd like to provide a fix for this but as you guys know I'm new so what would be the best way for me to do this?

Thanks!

**Comment by mazipan** [comment]
Let me merge first for @robwgreenjr changes, and @nickjlee can follow steps in the readme for contributing and make a fix for this.

**Comment by mazipan** [comment]
You can make a change in file README.KR.md ya @nickjlee and sent the pull request to this repo

**Comment by nickjlee** [comment]
@mazipan made those changes and a PR #209

**Comment by emanoelopes** [comment]
I can translate to Portuguese-Br.
