### ISSUE TITLE
Auto comment failed

### ISSUE THREAD

**Issue by mazipan** [mazipan/hello-open-source#315]
Currently, Actions for auto comment is failed.
I think it because most of PR is forked.
Need to use direct hit using cURL on bash script using personal access token.

**Comment by cao-donald** [comment]
I think it's fix already - PR passed on Workflow.

**Comment by mazipan** [comment]
Not sure, I am not create any fix for this.

**Comment by Shubham56-droid** [comment]
dude  i  just  dont  know how  to  do this  open  source  contribution   can  somebody  help??

**Comment by mazipan** [comment]
Please try to read the instructions in the reader.md carefully @Shubham56-droid

**Comment by Shubham56-droid** [comment]
thanks  bro
