### ISSUE TITLE
Put Readme translations in translations directory

### ISSUE THREAD

**Issue by Preet-Sojitra** [mazipan/hello-open-source#509]
Root of the project is looking bit cluttered because of all the Readme translations present in the root only. 

To solve this, we can create a directory with name `Translations` which will contains all the translations of the Readme file. We can link this Translations in main `README.md`. This will make this project more structured and bit less cluttered.

What are your thoughts on this?

**Comment by mazipan** [comment]
Good idea

**Comment by Preet-Sojitra** [comment]
> Good idea

So I would like to work on this. Can you assign this to me?

**Comment by Preet-Sojitra** [comment]
ok thanks, working on this 👍
