### ISSUE TITLE
File not following the guidelines 

### ISSUE THREAD

**Issue by RavindraP04** [mazipan/hello-open-source#597]
**Describe the bug**
The file [vidhijain.js](https://github.com/mazipan/hello-open-source/blob/master/people/vidhijain.js) does not follows the guidelines mentioned in the Readme.md

**To Reproduce**
When we raise a new PR it shows error in the Lint Files, I have mentioned the screenshot of the same below

**Screenshots**
![image](https://github.com/mazipan/hello-open-source/assets/98400348/2f111315-8710-4308-80be-98dad19f07ec)

**Comment by RavindraP04** [comment]
@mazipan Please look at this issue

**Comment by mazipan** [comment]
Closed by running GitHub Action manually to purge the data
