### ISSUE TITLE
Add German Translation

### ISSUE THREAD

**Issue by Durgesh4993** [mazipan/hello-open-source#661]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jonasermert** [comment]
Bezieht sich Ihre Funktionsanfrage auf ein Problem? Bitte beschreiben Sie es.
Eine klare und prägnante Beschreibung des Problems. Beispiel. Ich bin immer frustriert, wenn [...]

Beschreiben Sie die Lösung, die Sie sich wünschen
Eine klare und prägnante Beschreibung dessen, was Sie sich wünschen.

Beschreiben Sie die Alternativen, die Sie in Betracht gezogen haben
Eine klare und prägnante Beschreibung aller alternativen Lösungen oder Funktionen, die Sie in Betracht gezogen haben.

Zusätzlicher Kontext
Fügen Sie hier weitere Informationen oder Screenshots zu Ihrer Anfrage hinzu.

**Comment by Lenzork** [comment]
Don't we have a german translation? (9c831046649286b83f8586e02d39123cd26123b9). I believe this issue can be closed 🤔
